import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Text } from '@/shared/Text';
export default function FormField({ label, value, onChangeText, onBlur, onFocus, placeholder, icon, prefix, error, autoCapitalize, multiline = false, numberOfLines = 4, editable = true, secureTextEntry = false, type, }) {
    const containerClass = multiline
        ? `flex flex-row items-start min-h-textarea px-4 py-3 gap-3 rounded-lg border border-subtle-border ${editable ? 'bg-card' : 'bg-muted'}`
        : `flex flex-row items-center h-input px-4 gap-3 rounded-lg border border-subtle-border ${editable ? 'bg-card' : 'bg-muted'}`;
    const inputType = secureTextEntry ? 'password' : (type ?? 'text');
    return (_jsxs("div", { className: "flex flex-col gap-2", children: [_jsx(Text, { variant: "label", className: "font-semibold text-foreground", children: label }), _jsxs("div", { className: containerClass, children: [icon ? _jsx("div", { className: multiline ? 'pt-1' : '', children: icon }) : null, prefix ? (_jsx(Text, { variant: "body", className: "font-medium text-muted-foreground", children: prefix })) : null, multiline ? (_jsx("textarea", { className: `flex-1 text-body bg-transparent border-0 outline-none resize-none w-full ${editable ? 'text-foreground' : 'text-muted-foreground'}`, value: value, onChange: (e) => onChangeText(e.target.value), onBlur: onBlur, onFocus: onFocus, placeholder: placeholder, style: { minHeight: numberOfLines * 24 /* computed from prop — cannot be a static token */ }, disabled: !editable })) : (_jsx("input", { className: `flex-1 text-body bg-transparent border-0 outline-none w-full ${editable ? 'text-foreground' : 'text-muted-foreground'}`, value: value, type: inputType, onChange: (e) => onChangeText(e.target.value), onBlur: onBlur, onFocus: onFocus, placeholder: placeholder, autoCapitalize: autoCapitalize, disabled: !editable }))] }), error ? (_jsx(Text, { variant: "caption", className: "text-destructive pl-1", children: error })) : null] }));
}
